language: node_js

# until we cache contributions somewhere
# https://github.com/putaindecode/putaindecode.fr/issues/218
git:
  depth: 100000

# http://docs.travis-ci.com/user/notifications/
notifications:
  irc:
    channels:
      - "irc.freenode.org#putaindecode"
    on_success: always
    on_failure: always
    use_notice: true
    skip_join: true

# http://docs.travis-ci.com/user/caching/
cache:
  directories:
    - node_modules

# http://docs.travis-ci.com/user/build-configuration/
script:
  # we need --global because of how gulp-gh-pages works (with another clone elsewhere)
  - git config --global user.name "Travis-CI"
  - git config --global user.email "mail+travis@putaindecode.fr"
  - npm run travis

env:
  global:
    - secure: ghMMp0kKWiZvqhHDROxGPQOARnIYJIeZcu0RVgVHkNNFOeSoJg9X+zBfDn6plQyo59ogKisdyVJgSh7IS+HiF98lhEm3qHd4Cbs136m5Wz0FjhIbFsaFij2OT5ECco+sAkgqniv3rl+5IZMvDlMh8g0+jkhVRvpF3I/ye0ckMXo=
    - GH_OWNER: putaindecode
    - GH_PROJECT_NAME: putaindecode.fr
