language: node_js

# http://docs.travis-ci.com/user/notifications/
notifications:
  irc:
    channels:
      - "irc.freenode.org#putaindecode"
    on_success: always
    on_failure: always
    # template:
    #   - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    #   - "Change view : %{compare_url}"
    #   - "Build details : %{build_url}"
    use_notice: true
    skip_join: true
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1963aded18e129703057
    on_start: true

# http://docs.travis-ci.com/user/caching/
cache:
  directories:
    - node_modules

# http://docs.travis-ci.com/user/build-configuration/
script:
  # we need --global because of how gulp-gh-pages works (with another clone elsewhere)
  - git config --global user.name "Travis-CI"
  - git config --global user.email "mail+travis@putaindecode.fr"
  - npm run travis

env:
  global:
    # MoOx
    - secure: 4PEqVqjHxXE6qQ3t+YoPyTrxT+3+W4il43NjCCdHrDucv5UQ3ceESoDxAFWO62W+HYGpp71zUxyiU+afgMjskwvAO1AFXvu6MBVuo3DycmD4uNChUGFAeBapM6Kul4Y+A8MXoo21//8yFX3oDvCa/VC3pRKp4utx2JhDDLl1dOM=
    # bloodyowl
    - secure: zOkI7imfGSlOTOzxLl3bCjEvvMb0clcAqEChf+mKY9nqx7cxHsUNY4vR6YbL8fSHNI27HromGpEh8xYolC/UArJ30/GDNSfv/wroQlBuTEYdoqup+f3o18AKG1i6fkc0frowTD9PpeRr56t3TiTrhCpNEDE0QaexDKMfuw5dUXo=
