language: node_js

# http://docs.travis-ci.com/user/notifications/
notifications:
  irc:
    channels:
      - "irc.freenode.org#putaindecode"
    on_success: change
    on_failure: always
    # template:
    #   - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    #   - "Change view : %{compare_url}"
    #   - "Build details : %{build_url}"
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1963aded18e129703057
    on_start: true

cache:
  directories:
    - node_modules
