language: node_js

notifications:
  irc:
    - "irc.freenode.org#putaindecode"
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1963aded18e129703057
    on_start: true

cache:
  directories:
    - node_modules
