language: node_js
before_install:
# global requirements
  - make init
  - make install
# local requirements
  - make update
# for some test with dates
  - sudo cp /usr/share/zoneinfo/Europe/Paris /etc/localtime

notifications:
  irc: "irc.freenode.org#p!"
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1963aded18e129703057
    #on_success: always  # options: [always|never|change] default: always
    #on_failure: always  # options: [always|never|change] default: always
    on_start: true     # default: false

cache:
  directories:
    - bower_components
    - node_modules
