sudo: false

language: node_js
node_js:
  - 4

# contributors task: need all commits until we cache contributions somewhere else https://github.com/putaindecode/putaindecode.fr/issues/218
git:
  depth: 100000

before_script:
  # for headless browsers
  # http://docs.travis-ci.com/user/gui-and-headless-browsers/
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  # gh-pages: because of how gulp-gh-pages works (with a clone), --global is required
  - git config --global user.name "Travis-CI"
  - git config --global user.email "mail+travis@putaindecode.fr"

env:
  global:
    # GH_TOKEN
    - secure: d1VZ29IbfOn0Re774eOWFpCcSLMd3N49ehmMOF8NiAQBV30NddTr5GVua19sMfCBVryHVu5MaaD+xf8Qr1fANqZveFhjIdTsTRLt7BkfxpmrWwHKn6g1szQq6KMCUECtHToe9qrCwA/UC0p4+rNofd3PnlF51dTPvP8ZG1Yy7U0=
    - GIT_DEPLOY_REPO=https://$GH_TOKEN@github.com/putaindecode/putaindecode.fr.git

deploy:
  skip_cleanup: true
  provider: script
  script: ./scripts/deploy.sh
  on:
    branch: master
